# Generated by Django 4.2.1 on 2023-06-04 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posts",
            name="location",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
